=== Frogenius/XML-projekt/spisok.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
	  <xs:documentation xml:lang="pl">
	   <xs:appInfo>List participants</xs:appInfo>
		  This Schema defines a table with participants to competition
	  </xs:documentation>
	</xs:annotation>


	<xs:simpleType name="FIO">
		<xs:restriction base="xs:string">
		  <xs:minLength value="5"/>
		  <xs:maxLength value="50"/>
		  <xs:pattern value="([a-zA-Z ])*"/>
		</xs:restriction>
	</xs:simpleType>
	
    <xs:complexType name="postadrsh">
        <xs:sequence>
            <xs:element name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">									
						<xs:pattern value="[a-zA-Z ]*"/>
					</xs:restriction>
				</xs:simpleType>						  
			</xs:element>  						  
			<xs:element type="xs:string" name="street"/>
			<xs:element type="xs:string" name="city"/>
			<xs:element type="xs:string" name="state"/>
			<xs:element type="xs:decimal" name="zip"/>						  
		</xs:sequence>
		<xs:attribute type="xs:string" name="country" default="PL"/>
	</xs:complexType>
    	

	<xs:element name="group">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="name" use="required"/>
                    <xs:attribute type="xs:string" name="time" use="optional"/>
					<xs:attribute type="xs:string" name="limit_time" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
	
   <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        
		<xs:element type="xs:string" name="DocumentName"/>
		
        <xs:element name="competition">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:date" name="date" use="required"/>
                <xs:attribute type="xs:time" name="time" use="required"/>
                <xs:attribute type="xs:string" name="place" use="optional"/>
                <xs:attribute type="xs:byte" name="building" use="optional"/>
                <xs:attribute type="xs:string" name="sponsor" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
		
        <xs:element name="equipment">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="item" maxOccurs="10" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>	
    
        <xs:element name="participants">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="participant" maxOccurs="100" minOccurs="0">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element type="xs:string" name="member"/>
                    <xs:element name="contacts">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="phone"/>
                          <xs:element type="xs:string" name="email"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:date" name="sDate"/>
                    <xs:element type="xs:date" name="birfday"/>
                    <xs:element type="xs:boolean" name="experience" default="true"/>
                    <xs:element type="xs:anyURI" name="photo"/>
                    <xs:element type="xs:anyURI" name="url"/>
					<xs:element type="postadrsh" name="postadr"/>										
										
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="crew" use="required"/>
                </xs:complexType>				
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      
        <xs:element name="type">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="buildering">
                <xs:complexType>
                  <xs:sequence>
                    
					<xs:element ref="group" maxOccurs="5" minOccurs="0"/>
					
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="start_time"/>
                  <xs:attribute type="xs:string" name="finish_time"/>
                  <xs:attribute type="xs:string" name="limit_time"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="szybkość">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="group" maxOccurs="5" minOccurs="0"/>                      
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="trudność">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="group" maxOccurs="1" minOccurs="0"/>                      
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
          </xs:complexType>
        </xs:element>
		
		
        <xs:element name="age_groups">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="unior" default="12-16"/>
              <xs:element type="xs:string" name="students" default="16-24"/>
              <xs:element type="xs:string" name="profy" default="16-40"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="comment"/>
          </xs:complexType>
        </xs:element>
		
		
        <xs:element name="judges">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="trasa">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="osoba" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="class" use="optional"/>
                            <xs:attribute type="xs:string" name="place" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="secretary" maxOccurs="2" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="osoba"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
		
		      
		
		<xs:element type="FIO" name="main_judge"/>
		  	
		
		<xs:element type="FIO" name="secretary_main"/>
		
		<xs:element type="FIO" name="doctor" default="Kim Vladislav"/>		
		
        <xs:element type="xs:string" name="leader" fixed="Jumaev Maksut"/>
		
		<xs:element name="photographer">
		  <xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Bayev Serik"/>
				<xs:enumeration value="Isaev Askar"/>
				<xs:enumeration value="Belov Ayan"/>
			</xs:restriction>		  
		  </xs:simpleType>
		</xs:element>	  
	  
	  
	  </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Frogenius/XML-projekt/spisok.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spisok.xsd">
    <DocumentName>Rock climbing</DocumentName>
	
	<competition name="closing of the season 2020" date="2020-12-22" time="10:00:00" place="City Center" building="3" sponsor="FORC">Rock climbing</competition>
    
	<equipment>
		<item>rock shoes</item>
		<item>climbing harness</item>
		<item>carbine</item>
	</equipment>
		
	<participants>
	
		<participant id="1" crew="Pacifica">			
			<member>Irina</member>
			<contacts>
				<phone>+701 444444</phone>
				<email>Irina@gmail.com</email>
			</contacts>
			<sDate>2020-05-21</sDate>
			<birfday>2000-07-04</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
		<participant id="2" crew="Pacifica">			
			<member>Hanna</member>
			<contacts>
				<phone>+701 55555</phone>
				<email>Hanna@gmail.com</email>
			</contacts>l>
			<sDate>2020-05-21</sDate>
			<birfday>1995-07-22</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
		<participant id="3" crew="Batman">			
			<member>Eliza</member>
			<contacts>
				<phone>+701 666666</phone>
				<email>Eliza@gmail.com</email>
			</contacts>
			<sDate>2020-05-21</sDate>
			<birfday>2001-06-11</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
		<participant id="3" crew="Batman">			
			<member>Sergey</member>
			<contacts>
				<phone>+701 77777</phone>
				<email>Sergey@gmail.com</email>
			</contacts>l>
			<sDate>2020-05-21</sDate>
			<birfday>2001-05-11</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
		 <participant id="3" crew="Tango">
			<member>Anton</member>
			<contacts>
				<phone>+701 888888</phone>
				<email>Anton@gmail.com</email>
			</contacts>
			<sDate>2020-05-21</sDate>
			<birfday>2001-04-11</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
		<participant id="3" crew="Tango">
			<member>Sveta</member>
			<contacts>
				<phone>+701 999999</phone>
				<email>Sveta@gmail.com</email>
			</contacts>
			<sDate>2020-05-21</sDate>
			<birfday>2001-03-11</birfday>
			<experience>true</experience>
			<photo>photo1.jpg</photo>
			<url>http://site.com</url>
			<postadr country="KZ">
				<name>Tanya Frolova</name>
				<street>52 Orbita-3</street>
				<city>Almaty</city>
				<state>Almaty</state>
				<zip>0500</zip>
			</postadr>				
		</participant>
	</participants>
	
	<type name="Rodzaje wspinaczki">
		<buildering start_time="09:30" finish_time="17:00" limit_time="90sec"><group name="A" time="09:30" /><group name="B" time="12:30" /></buildering>
		<szybko¶æ><group name="A" time="9:30" limit_time="300sec" /><group name="B" time="10:30" /><group name="C" time="15:00" /></szybko¶æ>
		<trudno¶æ><group name="A" time="16:00" limit_time="600sec" /></trudno¶æ>
	</type>
	
	<age_groups comment="liczba pe³nych lat">
		<unior>12-16</unior>
		<students>16-24</students>
		<profy>16-40</profy>
	</age_groups>
	
	<judges>
		<trasa>
			<osoba class="1" place="ska³a">Kugachenko Roman</osoba>
			<osoba class="1" place="ska³a">Dymel Wojciech</osoba>
			<osoba class="2" place="timer">Kocot Bart³omiej</osoba>
		</trasa>
		<secretary>
			<osoba>
				Belova Anna
			</osoba>	
		</secretary>
	</judges>
	
	
	<main_judge>Ilinsky Ervand</main_judge>
	<secretary_main>Ilinskaya Mariam</secretary_main>
	<doctor>Kim Vladislav</doctor>	
	<leader>Jumaev Maksut</leader>
	<photographer>Bayev Serik</photographer>
	
	
</document>
